version: "3.7"
services:
 
 app:
  build: .
  ports:
   - "5000:5000" 
  environment:
   DBUSER: adex
   DBPASS: adex
   DBHOST: db
   DBNAME: adex
   restart: always
   FLASK_APP: app.py
  depends_on:
   - db

 db:
  image: postgres
  restart: always
  ports:
   - "5001:5000" 
  environment:
   POSTGRES_USER: adex
   POSTGRES_PASSWORD: adex
   POSTGRES_DB: adex