version: "3.9"
services:
 app1:
  build: . 
  restart: always
  ports:
   - "5005:5000"
  environment:
   FLASK_ENV: development
   DBUSER: adex1
   DBPASS: adex1
   DBHOST: db
   DBNAME: adex

  depends_on:
   - db
 app2:
  build: . 
  restart: always
  ports:
   - "5006:5000"
  environment:
   FLASK_ENV: development
   DBUSER: adex2
   DBPASS: adex2
   DBHOST: db
   DBNAME: adex
  depends_on:
   - db
 db:
  image: "postgres"
  volumes:
   - ./init.sh:/docker-entrypoint-initdb.d/init.sh
  environment:   
   POSTGRES_DB: adex
   POSTGRES_USER: adex
   POSTGRES_PASSWORD: adexone
   restart: always

 registry:
  image: 'registry:2'
  container_name: registry
  restart: always
  ports:
    - 5000:5000
  volumes:
    - "/storage/registry/data:/var/lib/registry"
    - "storage/registry/certs:/certs"
    - "storage/registry/auths:/auths"
  environment:
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/example.com.crt
    - REGISTRY_HTTP_TLS_KEY=/certs/example.com.key
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd